# Generated by Django 5.0.4 on 2024-04-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cruds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('educationLevel', models.CharField(max_length=255)),
                ('workExperience', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'simp_crud_empl',
            },
        ),
    ]
